server:
  port: 9003

spring:
  application:
    name: 'redis-lock'
  redis:
    port: 6379
    database: 0
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大阻塞等待时间
        max-idle: 8
        # 最小空闲连接
        min-idle: 0
    host: 127.0.0.1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    # 指示此实例是否应向 eureka 服务器注册其信息以供其他人发现。 在某些情况下，您不希望发现您的实例，而只想发现其他实例
    register-with-eureka: true
    # 自己的这个服务不是注册中心。仅仅向注册中心注册
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/




