server:
  port: 10001

spring:
  application:
    name: 'business'
  redis:
    port: 6379
    database: 0
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大阻塞等待时间
        max-idle: 8
        # 最小空闲连接
        min-idle: 0
    host: 127.0.0.1

eureka:
  client:
    # 指示此实例是否应向 eureka 服务器注册其信息以供其他人发现。 在某些情况下，您不希望发现您的实例，而只想发现其他实例
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/

